---

- name: Uninstall incompatible packages
  ansible.builtin.apt:
    name:
      - xmonad
      - libghc-xmonad-dev
      - libghc-xmonad-contrib-dev
    state: absent
  become: true

- name: Create folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ CONFIG_DIR }}/xmonad/lib"
    - "{{ HOME }}/.cache/xmonad"
    - "{{ HOME }}/.local/share/xmonad"

################
# Configurtion #
################

- name: Link configuration
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ item | replace(REPO_FILES, CONFIG_DIR) }}"
    state: link
  with_fileglob: "{{ REPO_FILES }}/xmonad/*"

- name: Template colors
  ansible.builtin.template:
    src: "Colors.hs.j2"
    dest: "{{ CONFIG_DIR }}/xmonad/lib/Colors.hs"

# - name: Template eww files
#   ansible.builtin.template:
#     src: "{{ item }}.j2"
#     dest: "{{ CONFIG_DIR }}/eww/{{ item }}"
#   loop:
#     - "eww.scss"

###################
# Build & install #
###################
# Untested from here onward

- name: Install packages
  ansible.builtin.apt:
    name:
      - haskell-stack
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxss-dev
  become: true

- name: Clone core repo [fork]
  ansible.builtin.git:
    repo: "https://github.com/deved99/xmonad"
    dest: "{{ CONFIG_DIR }}/xmonad/xmonad"
    version: "1.17-opaque-border"
    update: false

- name: Clone contrib repo
  ansible.builtin.git:
    repo: "https://github.com/xmonad/xmonad-contrib"
    dest: "{{ CONFIG_DIR }}/xmonad/xmonad-contrib"
    version: "v0.17.0"
    update: false


- name: Copy stack.yaml
  ansible.builtin.copy:
    src: stack.yaml
    dest: "{{ CONFIG_DIR }}/xmonad/stack.yaml"
  
- name: stack install
  ansible.builtin.command:
    cmd: stack install
    chdir: "{{ CONFIG_DIR }}/xmonad"

##########################
# XSession configuration #
##########################

- name: Copy xsession.desktop
  ansible.builtin.template:
    src: xsession.desktop.j2
    dest: /usr/share/xsessions/xsession.desktop
  become: true

- name: Copy ~/.Xsession # Move this to ~/.config/xmonad?
  ansible.builtin.copy:
    src: Xsession
    dest: "{{ HOME }}/.Xsession"
    mode: 'u+x'
