---

- name: Packages for Apt over HTTPS
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  become: yes

- name: Install gpg key
  block:
    - name: Remove old gpg public key
      ansible.builtin.file:
        path: "/etc/apt/keyrings/nodesource.gpg"
        state: absent
    - name: Download nodesource public key
      ansible.builtin.get_url:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        dest: "/tmp/nodesource.gpg"
    - name: Download docker public key
      ansible.builtin.command: >-
        gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg /tmp/nodesource.gpg
  become: yes

- name: Add repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/nodesource.gpg]
      https://deb.nodesource.com/node_18.x
      jammy main
  become: yes


- name: Install packages
  ansible.builtin.apt:
    name: nodejs
  become: yes
