---

- name: Ensure {{ CONFIG_DIR }}/bash exists
  ansible.builtin.file:
    path: "{{ CONFIG_DIR }}/bash"
    state: directory

- name: Install commands
  ansible.builtin.apt:
    name:
      # Script to rename with a sed like syntax
      - rename
      # Pretty print and query jsons
      - jq
      # Keep history of common dirs and easily cd into them
      - autojump
      # Fallback editor
      - vim
      # Info about domain/ip
      - whois 
      # Shorter man
      - tldr
  become: yes

- name: Link .bashrc and .profile
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: "{{ REPO_FILES }}/bash/bashrc"
      dest: "{{ HOME }}/.bashrc"
    - src: "{{ REPO_FILES }}/bash/profile"
      dest: "{{ HOME }}/.profile"

- name: Link snippets to config dir
  ansible.builtin.file:
    src: "{{ src }}"
    dest: "{{ dest }}"
    state: link
  vars:
    src: "{{ item }}"
    dest: "{{ item | replace(REPO_FILES, CONFIG_DIR) }}"
  with_fileglob: "{{ REPO_FILES }}/bash/*.sh"
