#!/bin/sh

REMOTE=dropbox:Notes
LOCAL=$HOME/Notes
TEMP=/tmp/Notes.tmp

echo Syncing remote and local notes
# Print variables
echo Remote directory: $REMOTE
echo Local directory: $LOCAL
echo Temp directory: $TEMP

# Get remote Notes
rclone sync $REMOTE $TEMP
rsync -avu $LOCAL $TEMP
rsync -avu $TEMP $LOCAL
rclone sync $TEMP $REMOTE
