---

####################
# Install packages #
####################

- name: Add ppa for Emacs 28
  ansible.builtin.apt_repository:
    repo: ppa:kelleyk/emacs
  become: yes

- name: Install Emacs and related packages
  ansible.builtin.apt:
    name:
      - emacs28
      - rclone
      - texlive-full
  become: yes

##############################
# Create configuration files #
##############################

# Commented lines needed by straight el

# - name: Ensure directories exist
#   ansible.builtin.file:
#     path: "{{ CONFIG_DIR }}/emacs/straight/versions"
#     state: directory

- name: Symlink configuration
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: "{{ REPO_FILES }}/emacs/init.el"
      dest: "{{ CONFIG_DIR }}/emacs/init.el"
    - src: "{{ REPO_FILES }}/emacs/init.org"
      dest: "{{ CONFIG_DIR }}/emacs/init.org"
    # - src: "{{ REPO_FILES }}/emacs/early-init.el"
    #   dest: "{{ CONFIG_DIR }}/emacs/early-init.el"
    # - src: "{{ REPO_FILES }}/emacs/versions/default.el"
    #   dest: "{{ CONFIG_DIR }}/emacs/straight/versions/default.el"

- name: Copy theme
  ansible.builtin.copy:
    src: "themes/{{ CS_EMACS }}"
    dest: "{{ CONFIG_DIR }}/emacs/theme.el"

- name: Copy rclone configuration
  ansible.builtin.file:
    src: "{{ REPO_SECRETS }}/rclone"
    dest: "{{ CONFIG_DIR }}/rclone"
    state: link

- name: Copy notes-sync to .local/bin
  ansible.builtin.copy:
    src: scripts/notes-sync
    dest: "{{ LOCAL_BIN }}/notes-sync"
    mode: u+x

###################
# SystemD related #
###################
    
- name: Install emacs related services service
  ansible.builtin.copy:
    src: systemd-user/
    dest: "{{ SYSTEMD_DIR }}/"

- name: Enable and start emacs service
  ansible.builtin.systemd:
    name: emacs
    scope: user
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Enable and start notes-sync
  ansible.builtin.service:
    name: notes-sync.timer
    scope: user
    enabled: yes
    state: started
