- name: Add ppa for Emacs 28
  ansible.builtin.apt_repository:
    repo: ppa:kelleyk/emacs
  become: yes

- name: Uninstall incompatible Emacs
  ansible.builtin.apt:
    name:
      - emacs28
      - emacs
    state: absent
  become: yes

- name: Install Emacs and related packages
  ansible.builtin.apt:
    name: emacs28-nativecomp
  become: yes
