---

- name: Install Python3 and pip (ubuntu)
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python-is-python3
  when: distro_short == "ubuntu"
  become: true

- name: Install Python3 and pip (arch)
  community.general.pacman:
    name:
      - python
      - python-pip
  when: distro_short == "arch"
  become: true
