---
- name: Configuring {{ PROFILE }}
  hosts: localhost
  # tasks:
  #   - name: Test
  #     ansible.builtin.debug:
  #       msg: "{{ BASE16 }}"
  roles:
    # Basics
    - prepare
    - shell
    # Graphical
    - role: awesome
      tags: graphical
    - role: kitty # Terminal
      tags: graphical
    - role: emacs # Editor
      tags: graphical
    - role: menu # Well, I guess you can tell
      tags: graphical
    - role: brave # Browser
      tags: graphical
    # Optional roles
    - role: mpd # Music
      tags: music
    - role: virsh
      tags: virsh
