---
- name: Configuring {{ PROFILE }}
  hosts: localhost
  vars:
    distro_shorts:
      Archlinux: arch
      Ubuntu: ubuntu
    distro_short: "{{ distro_shorts[ansible_facts['distribution']] }}"
  pre_tasks:
    - name: Become password check
      ansible.builtin.command: whoami
      become: true
      tags: always
  roles:
    # Basics
    - role: base.prepare
      tags: base,prepare
    - role: term.bash
      tags: base,shell
    # Window Managers
    - role: wm.awesome
      tags: graphical,awesome
    - role: wm.xmonad
      tags: xmonad
    - role: wm.bspwm
      tags: bspwm
    # WM utilities
    - role: wm.dunst
      tags: dunst
    - role: wm.eww
      tags: eww
    - role: wm.menu
      tags: graphical,menu
    # Terminal
    - role: term.alacritty
      tags: graphical,alacritty
    - role: term.kitty
      tags: kitty
    # Programs
    - role: program.emacs
      tags: emacs
    - role: program.neovim
      tags: base,neovim
    - role: program.brave
      tags: brave
    - role: program.signal
      tags: signal
    # Audio related
    - role: audio.pipewire
      tags: graphical,pipewire
    - role: audio.mpd # Music
      tags: mpd
    # Programming 
    - role: langs.rust
      tags: rust
    - role: langs.javascript
      tags: javascript
    - role: langs.python
      tags: python
    # Virtualization
    - role: virt.docker
      tags: docker
    - role: virt.libvirt
      tags: libvirt
    # Miscellaneous programs
    - role: program.drawio
      tags: drawio
