---
- name: Configuring {{ PROFILE }}
  hosts: localhost
  # tasks:
  #   - name: Test
  #     ansible.builtin.debug:
  #       msg: "{{ BASE16 }}"
  roles:
    # Basics
    - role: prepare
      tags: always
    - role: shell
      tags: always
    # Graphical
    - role: awesome
      tags: graphical
    - role: kitty # Terminal
      tags: graphical
    - role: emacs # Editor
      tags: graphical
    - role: menu # Well, I guess you can tell
      tags: graphical
    - role: brave # Browser
      tags: graphical
    ## Audio related
    - role: pipewire
      tags: graphical
    - role: mpd # Music
      tags: music
    ## Miscellaneous
    # Docker
    - role: docker
      tags: docker
    # Libvirt
    - role: virsh
      tags: virsh
