---
- name: Configuring {{ PROFILE }}
  hosts: localhost
  # tasks:
  #   - name: Test
  #     ansible.builtin.debug:
  #       msg: "{{ BASE16 }}"
  roles:
    # Basics
    - role: prepare
      tags: base,prepare
    - role: bash
      tags: base,shell
    # Graphical
    - role: awesome
      tags: graphical,awesome
    - role: kitty # Terminal
      tags: graphical,kitty
    - role: emacs # Editor
      tags: graphical,emacs
    - role: menu # Well, I guess you can tell
      tags: graphical,menu
    - role: brave # Browser
      tags: graphical,brave
    ## Audio related
    - role: pipewire
      tags: graphical,pipewire
    - role: mpd # Music
      tags: mpd
    ## Miscellaneous
    # Docker
    - role: docker
      tags: docker
    # Libvirt
    - role: libvirt
      tags: libvirt
