---
- name: Configuring {{ PROFILE }}
  hosts: localhost
  # tasks:
  #   - name: Test
  #     ansible.builtin.debug:
  #       msg: "{{ BASE16 }}"
  roles:
    # Basics
    - role: base.prepare
      tags: base,prepare
    - role: term.bash
      tags: base,shell
    # Window Managers
    - role: wm.awesome
      tags: graphical,awesome
    - role: wm.xmonad
      tags: graphical,xmonad
    ## Terminal
    - role: term.alacritty
      tags: graphical,alacritty
    - role: term.kitty
      tags: kitty
    ## Editor
    - role: program.emacs # Editor
      tags: graphical,emacs
    ## Menu
    - role: wm.menu
      tags: graphical,menu
    ## Browser
    - role: program.brave # Browser
      tags: graphical,brave
    ## Audio related
    - role: audio.pipewire
      tags: graphical,pipewire
    - role: audio.mpd # Music
      tags: mpd
    ## Miscellaneous
    # Docker
    - role: virt.docker
      tags: docker
    # Libvirt
    - role: virt.libvirt
      tags: libvirt
