---
- name: Configuring {{ PROFILE }}
  hosts: localhost
  # tasks:
  #   - name: Test
  #     ansible.builtin.debug:
  #       msg: "{{ BASE16 }}"
  roles:
    - prepare
    - awesome # WM
    - shell
    - kitty # Terminal
    - emacs # Editor
    - menu # Well, I guess you can tell
    - mpd # Music
