#+title: dotfiles

* Overview
This repo contains my dotfiles and an Ansible playbook.

My dotfiles are in the ~files/~ directory, which is structured like this:
#+begin_src
files
├── awesome
│   ├── rc.lua
│   ├── rc.org
│   └── theme.lua
└── emacs
    ├── init.el
    └── init.org
#+end_src
Files ending with ~.org~ are [[https://orgmode.org][org]] files. These files can contain code
blocks, which can be extracted using [[https://orgmode.org/worg/org-contrib/babel/][Babel]] to create the configuration
files.

The Ansible playbook configures the machine and is further described
in its section. I usually run it using ~configure~ from this repo.
* Ansible playbook
The playbook is splitted into roles, each role dedicated to a program.

Planned roles:
- Brave browser
- Pipewire and Pulseaudio masking
** preparations
- Add autojump
** awesome
- Reload throws an error?
** menu
- Add the menuing part: right now it just install a dmenu script.
- Theme rofi.
** kitty
In the end, this will be my backup
** emacs
- Auto-tangle for org-files?
- vterm with multiple instances and shell integration
** mpd
- mpdscribble: why isn't it starting?
  Maybe it is waiting for mpd, which on start fails since ~/Music is
  not mounted?
