#!/usr/bin/env python3
import argparse

def getArgumentParser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    # Whether to copy script in $PATH
    parser.add_argument(
        '--install', dest = 'install', action = 'store_true',
        help = "install script in ~/.local/bin"
    )
    # Toggle or set colorscheme
    parser.add_argument(
        '-t', '--toggle', dest = 'colorscheme', action = 'store_const',
        const = "toggle",
        help = "toggle dark/light colorscheme"
    )
    parser.add_argument(
        '-s', '--set', dest = 'colorscheme', action = 'store',
        choices = ["dark", "light"],
        help = "set dark/light colorscheme as given"
    )
    return parser

## config
# read config file
# write config file

## Subroutins
# install this script in ~/.local/bin
# if --install
def install():
    print("I'm installing this.")
    playbook()

# launch the ansible
# if not --install
def playbook():
    print("I'm launching the playbook.")

def main():
   parsed = getArgumentParser().parse_args()
   print(parsed)

if __name__ == "__main__":
    main()
