#!/usr/bin/env python3
# Std
import argparse
from pathlib import Path
import os
import subprocess
# External
import yaml

def getArgumentParser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    # Whether to copy script in $PATH
    parser.add_argument(
        '--install', dest = 'install', action = 'store_true',
        help = "install script in ~/.local/bin"
    )
    # Toggle or set colorscheme
    parser.add_argument(
        '-t', '--toggle', dest = 'colorscheme', action = 'store_const',
        const = "toggle",
        help = "toggle dark/light colorscheme"
    )
    parser.add_argument(
        '--set', dest = 'colorscheme', action = 'store',
        choices = ["dark", "light"],
        help = "set dark/light colorscheme as given"
    )
    return parser

## Helpers
# TODO: accept config-this.yaml too
def get_config_path() -> str:
    config_dir = os.environ.get("XDG_CONFIG_DIR")
    if config_dir is None:
        config_dir = Path.home() / ".config"
    else:
        config_dir = Path(config_dir)
    return config_dir / "local" / "config-this.yml"

# read config file
def config_read() -> dict:
    with open(get_config_path()) as f:
        return yaml.safe_load(f)

## Subroutins
# install this script in ~/.local/bin
# if --install
def install(profile):
    cmd = [
        "ansible-playbook",
        "--extra-vars", "@vars/common.yml",
        "--extra-vars", f"@vars/{profile}.yml",
        "install.yml", "-K"
    ]
    subprocess.run(cmd)

# launch the ansible
# if not --install
def playbook(colorscheme: str):
    colorscheme = "{{" + colorscheme + "}}"
    cmd = [
        "ansible-playbook",
        "--extra-vars", "@vars/common.yml",
        "--extra-vars", f"@vars/{profile}.yml",
        "--extra-vars", f"CS={colorscheme}"
        "playbook.yml", "-K"
    ]
    subprocess.run(cmd)

def main():
    # parsed = getArgumentParser().parse_args()
    # print(parsed)
    get_variables("stable")

if __name__ == "__main__":
    main()
