---

- name: Install EWW (ubuntu)
  import_tasks: ubuntu.yml
  when: short_distro == "ubuntu"

- name: Install EWW (arch)
  kewlfft.aur.aur:
    name: eww
  become: true
  become_user: aur_builder
  when: short_distro == "arch"

- name: Copy systemd unit
  ansible.builtin.copy:
    src: eww.service
    dest: "{{ SYSTEMD_DIR }}/eww.service"


- name: Reload services
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
