---

- name: Install packages
  ansible.builtin.apt:
    name:
      - libgtk-3-dev
      - libpango1.0-dev
      - libgdk-pixbuf2.0-dev
      - libcairo2-dev
      - libc6
  become: true

- name: Clone directory
  ansible.builtin.git:
    repo: "https://github.com/elkowar/eww"
    dest: "{{ BUILD_DIR }}/eww"
    update: false

- name: Build
  ansible.builtin.command:
    cmd: "cargo +nightly build --release"
    chdir: "{{ BUILD_DIR }}/eww"

- name: Copy binary to local bin
  ansible.builtin.copy:
    src: "{{ BUILD_DIR }}/eww/target/release/eww"
    dest: "{{ LOCAL_BIN }}/eww"
    mode: "u+x"
    remote_src: true
