---

- name: Declare distro 
  ansible.builtin.set_fact:
    base_packages: "{{ base_packages_by_distro | map(attribute=distro_short) | flatten }}"
    base_packages_by_distro:
      # File
      - ubuntu: btrfs-progs # Filesystem I use for storage
        arch: btrfs-progs
      - ubuntu: borgbackup
        arch: borg
      - ubuntu: pass
        arch: pass
      # Connect with android
      - ubuntu: 
          - adb
          - fastboot
        arch: android-tools
      # Graphical
      - ubuntu: fonts-firacode
        arch: ttf-fira-code
      - ubuntu: pavucontrol
        arch: pavucontrol
      - ubuntu: mpv
        arch: mpv
      - ubuntu: wmctrl
        arch: wmctrl
      - ubuntu: arandr
        arch: arandr
      # Networking tools
      - ubuntu: nmap
        arch: nmap
      - ubuntu: traceroute
        arch: traceroute
      - ubuntu: sipcalc # Calculate CIDR span
        arch: sipcalc
      - ubuntu: nload # Network usage monitor
        arch: nload
      - ubuntu: whois
        arch: whois
      - ubuntu: net-tools
        arch: net-tools
      # Printers
      - ubuntu: printer-driver-gutenprint
        arch: gutenprint

# - name: Distro specific preparation steps (arch)
#   import_tasks: arch.yml
#   when: distro_short == "arch"

- name: Install base packages (ubuntu)
  ansible.builtin.apt:
    name: "{{ base_packages }}"
  become: true
  when: distro_short == "ubuntu"

- name: Install base packages (arch)
  community.general.pacman:
    name: "{{ base_packages }}"
  become: true
  when: distro_short == "arch"

- name: Ensure folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "755"
  loop:
    - "{{ BUILD_DIR }}"
    - "{{ LOCAL_BIN }}"
    - "{{ SYSTEMD_DIR }}"

- name: Install ufetch
  ansible.builtin.get_url:
    url: "{{ ufetch_url }}"
    dest: "{{ LOCAL_BIN }}/ufetch"
    mode: "755"
  vars:
    ufetch_url: "{{ ufetch_urls[distro_short] }}"
    ufetch_urls:
        arch: "https://gitlab.com/jschx/ufetch/-/raw/main/ufetch-arch"
        ubuntu: "https://gitlab.com/jschx/ufetch/-/raw/main/ufetch-ubuntu"
