---

- name: Install miscellaneous packages
  ansible.builtin.apt:
    name:
      # File
      - btrfs-progs # Filesystem I use for storage
      - borgbackup # backups
      - pass
      # Connect with android
      - adb
      - fastboot
      # Graphical
      - fonts-firacode
      - pavucontrol
      - mpv
      - wmctrl
      - arandr
      # Networking tools
      - nmap
      - traceroute
      - sipcalc # Calculate CIDR span
      - nload # Network usage monitor
      - net-tools # misc
      # Printers
      - printer-driver-gutenprint
  become: yes

- name: Ensure folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ BUILD_DIR }}"
    - "{{ LOCAL_BIN }}"
    - "{{ SYSTEMD_DIR }}"

- name: Install ufetch
  ansible.builtin.get_url:
    url: "{{ UFETCH_URL }}"
    dest: "{{ LOCAL_BIN }}/ufetch"
    mode: "755"
