---

- name: Install Alacritty (ubuntu)
  import_tasks: ubuntu.yml
  when: short_distro == "ubuntu"

- name: Install Alacritty (arch)
  import_tasks: arch.yml
  when: short_distro == "arch"

#############
# Configure #
#############

- name: Create configuration dir
  ansible.builtin.file:
    path: "{{ CONFIG_DIR }}/alacritty"
    state: directory

- name: Copy configuration
  ansible.builtin.template:
    src: "alacritty.yml"
    dest: "{{ CONFIG_DIR }}/alacritty/alacritty.yml"
