#!/usr/bin/env bash

bspwm-update_monitors.py &

bspc config window_gap 10
bspc config border_width 4
bspc config normal_border_color "#6e6a86" # black-alt
bspc config focused_border_color "#f6c177" # accent
bspc config active_border_color "#9ccfd8" # blue
bspc config presel_border_color "#eb6f92" # red

bspc config split_ratio 0.52
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config gapless_monocle true

pgrep -x sxhkd > /dev/null || sxhkd &
~/.screenlayout/default.sh
feh --bg-scale ~/bg.jpg
eww open monitor-one
eww open monitor-two

setxkbmap -layout us -variant altgr-intl -option caps:escape
pgrep -x alacritty > /dev/null || alacritty &

# For some reason sxhkd doesn't start correctly
sleep 5 && pkill -USR1 -x sxhkd >>/tmp/log
