- name: Create build dir
  ansible.builtin.file:
    path: "{{ BUILD_DIR }}/neovim"
    state: directory

- name: Install configuration dependencies
  ansible.builtin.apt:
    name: ripgrep
  become: true

- name: Download neovim deb
  ansible.builtin.get_url:
    url: "{{ NEOVIM_DEB_URL }}"
    dest: "{{ BUILD_DIR }}/neovim/neovim.deb"
  vars:
    NEOVIM_DEB_URL: "https://github.com/neovim/neovim/releases/download/v0.8.3/nvim-linux64.deb"

- name: Install neovim deb
  ansible.builtin.apt:
    deb: "{{ BUILD_DIR }}/neovim/neovim.deb"
  become: true

- name: Set neovim as an alternative to vi
  ansible.builtin.shell: >-
    update-alternatives --install /usr/bin/vi vi $(which nvim) 100
  become: true

