- name: Create build dir
  ansible.builtin.file:
    path: "{{ BUILD_DIR }}/neovim"
    state: directory

- name: Install configuration dependencies
  ansible.builtin.apt:
    name: ripgrep
  become: true

- name: Remove neovim (APT)
  ansible.builtin.apt:
    name: neovim
    state: absent
  become: true

- name: Download neovim (AppImage)
  ansible.builtin.get_url:
    url: "{{ NEOVIM_URL }}"
    dest: "/usr/bin/nvim"
    mode: "755"
  become: true
  vars:
    NEOVIM_URL: "https://github.com/neovim/neovim/releases/download/v0.9.4/nvim.appimage"

- name: Download Neovide (AppImage)
  ansible.builtin.get_url:
    url: "{{ NEOVIDE_URL }}"
    dest: "/usr/bin/neovide"
    mode: "755"
  become: true
  vars:
    NEOVIDE_URL: "https://github.com/neovide/neovide/releases/download/0.11.2/neovide.AppImage"

- name: Set neovim as an alternative to vi
  ansible.builtin.shell: >-
    update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 100
  become: true

