---

- name: Create folders
  ansible.builtin.file:
    path: "{{ XMONAD_DIR }}"
    state: directory

#################
# Configuration #
#################

- name: Link configuration
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ item | replace(REPO_FILES, CONFIG_DIR) }}"
    state: link
  with_fileglob: "{{ REPO_FILES }}/xmonad/*"

- name: Template colors
  ansible.builtin.template:
    src: "Colors.hs.j2"
    dest: "{{ XMONAD_DIR }}/lib/Colors.hs"

# - name: Template eww files
#   ansible.builtin.template:
#     src: "{{ item }}.j2"
#     dest: "{{ CONFIG_DIR }}/eww/{{ item }}"
#   loop:
#     - "eww.scss"
