---

- name: Become password check
  ansible.builtin.command: whoami
  become: true

- name: Install miscellaneous packages
  ansible.builtin.apt:
    name:
      # File
      - btrfs-progs
      - borgbackup
      # Password management
      - pass
      # Fonts
      - fonts-firacode
      # Audio
      - pavucontrol
      # Printers
      - printer-driver-gutenprint
  become: yes

- name: Ensure folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ BUILD_DIR }}"
    - "{{ LOCAL_BIN }}"
    - "{{ SYSTEMD_DIR }}"
