---

- name: Install miscellaneous packages
  ansible.builtin.apt:
    name:
      - btrfs-progs # Filesystem I use for storage
      - borgbackup # backups
      # Fonts
      - fonts-roboto
      - fonts-jetbrains-mono
      - pass
      - pavucontrol
  become: yes

- name: Ensure folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ BUILD_DIR }}"
    - "{{ LOCAL_BIN }}"
    - "{{ SYSTEMD_DIR }}"

- name: Install fonts
  ansible.builtin.unarchive:
    src: "{{ REPO_DIR }}/secret/fonts/{{ item }}"
    dest: "{{ LOCAL_DIR }}/share/fonts/"
  loop:
    - ttf-iosevka-15.5.0.zip 
    - ttf-iosevka-aile-15.5.0.zip
