---

- name: Download k3s-install.sh
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /root/k3s-install.sh
    mode: "500"

- name: Ensure additional modules are installed. (Raspberry)
  ansible.builtin.apt:
    name: linux-modules-extra-raspi
  when: is_raspberry is defined and is_raspberry

- name: Install the first controller
  ansible.builtin.import_tasks: first.yml
  when: first_controller == inventory_hostname

- name: Install the other controllers
  ansible.builtin.import_tasks: others.yml
  when: first_controller != inventory_hostname
