---

- name: Install brave
  ansible.builtin.apt:
    name: brave-browser
    state: present
  become: yes

- name: Install MPD (ubuntu)
  import_tasks: ubuntu.yml
  when: distro_short == "ubuntu"

- name: Install MPD (arch)
  kewlfft.aur.aur:
    name: brave-bin
  become: yes
  become_user: aur_builder
  when: distro_short == "arch"
