---

- name: Install kitty (ubuntu)
  ansible.builtin.apt:
    name: kitty
  become: yes
  when: distro_short == "ubuntu"

- name: Install kitty (arch)
  community.general.pacman:
    name: kitty
  become: yes
  when: distro_short == "arch"

- name: Ensure config dir exists
  ansible.builtin.file:
    name: "{{ CONFIG_DIR }}/kitty"
    state: directory

- name: Template config file
  ansible.builtin.template:
    src: kitty.conf
    dest: "{{ CONFIG_DIR }}/kitty/kitty.conf"
    
