alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -alhF'
alias la='ls -A'
alias ew='emacsclient -c'
alias ef='emacsclient -c --no-wait'
alias jclip='xclip -o | jq'
