---

- name: Install yarn (ubuntu)
  import_tasks: ubuntu.yml
  when: short_distro == "ubuntu"

- name: Install yarn (arch)
  community.general.pacman:
    name: yarn
  become: true
  when: short_distro == "arch"
