---

- name: Remove Rust from Aptitude (ubuntu)
  ansible.builtin.apt:
    name:
      - cargo
      - rustc
      - rust-all
      - rust-src
    state: absent
    autoremove: true
  become: yes
  when: distro_short == "ubuntu"

- name: Remove Rust from Pacman (arch)
  ansible.builtin.pacman:
    name:
      - rust
      - rust-src
    state: absent
  become: yes
  when: distro_short == "arch"

- name: Install rustup
  block:
    - name: Download rustup-init.sh
      ansible.builtin.get_url:
        url: "https://sh.rustup.rs"
        dest: "{{ RUSTUP_INIT }}"
    - name: Execute rustup-init.sh
      ansible.builtin.command:
        cmd: "sh {{ RUSTUP_INIT }} -y --no-modify-path"
        creates: "{{ CARGO_BIN }}/rustup"
  vars:
    RUSTUP_INIT: "{{ BUILD_DIR }}/rust-init.sh"

- name: Download toolchains
  ansible.builtin.command:
    cmd: "{{ CARGO_BIN }}/rustup toolchain install {{ item }}"
    creates: "{{ HOME }}/.rustup/toolchains/{{ item }}-*"
  loop:
    - stable
    - nightly

- name: Install needed components
  ansible.builtin.command:
    cmd: "{{ CARGO_BIN }}/rustup component add {{ item }}"
  loop:
    - rust-analyzer
    - rust-src

- name: Find rust-analyzer binary
  ansible.builtin.command: >-
    {{ CARGO_BIN }}/rustup which --toolchain stable rust-analyzer
  register: RUST_ANALYZER_PATH

- name: Link rust-analyzer in bin
  ansible.builtin.file:
    path: "{{ CARGO_BIN }}/rust-analyzer"
    src: "{{ RUST_ANALYZER_PATH.stdout }}"
    state: link
