#!/bin/bash
$HOME/.config/set-monitors.sh

while read -r line; do
PROGRAM=$(echo $line | cut -d" " -f1)
pidof -q $PROGRAM || $line &
done <<EOF
picom --experimental-backends
thunderbird
flameshot
EOF
