#env:
#   TERM variable
#  
#   This value is used to set the `$TERM` environment variable for
#   each instance of Alacritty. If it is not present, alacritty will
#   check the local terminfo database and use `alacritty` if it is
#   available, otherwise `xterm-256color` is used.
#  TERM: alacritty

window:
  # Window padding (changes require restart)
  padding:
    x: 10
    y: 10
  # Allow terminal applications to change Alacritty's window title.
  dynamic_title: true

scrolling:
  history: 100000

# Font configuration
font:
  # Normal font family
  normal:
    family: Fira Code
  # Point size
  size: 8.0

# Colors (Tomorrow Night)
colors:
  primary:
    background: '{{ CS_BG }}'
    foreground: '{{ CS_FG }}'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor.
  #
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #cursor:
  #  text: CellBackground
  #  cursor: CellForeground

  # Normal colors
  normal:
    black:   '{{ CS_TERM[0] }}'
    red:     '{{ CS_TERM[1] }}'
    green:   '{{ CS_TERM[2] }}'
    yellow:  '{{ CS_TERM[3] }}'
    blue:    '{{ CS_TERM[4] }}'
    magenta: '{{ CS_TERM[5] }}'
    cyan:    '{{ CS_TERM[6] }}'
    white:   '{{ CS_TERM[7] }}'

  # Bright colors
  bright:
    black:   '{{ CS_TERM[8] }}'
    red:     '{{ CS_TERM[9] }}'
    green:   '{{ CS_TERM[10] }}'
    yellow:  '{{ CS_TERM[11] }}'
    blue:    '{{ CS_TERM[12] }}'
    magenta: '{{ CS_TERM[13] }}'
    cyan:    '{{ CS_TERM[14] }}'
    white:   '{{ CS_TERM[15] }}'
