---

- name: Install rofi
  ansible.builtin.apt:
    name:
      - rofi
  become: yes

- name: Copy dmenu's like script to local bin
  ansible.builtin.copy:
    src: dmenu
    dest: "{{ LOCAL_BIN }}/dmenu"
    mode: u+x

- name: Install menu
  import_tasks: menu.yml
