---

####################
# Install packages #
####################

- name: Add ppa for Emacs 28
  ansible.builtin.apt_repository:
    repo: ppa:kelleyk/emacs
  become: yes

- name: Install Emacs and related packages
  ansible.builtin.apt:
    name:
      - emacs28
      - rclone
  become: yes

##############################
# Create configuration files #
##############################

- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ CONFIG_DIR }}/emacs/straight/versions"
    state: directory

- name: Symlink configuration
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ item | replace(REPO_FILES, CONFIG_DIR) }}"
    state: link
  with_fileglob: "{{ REPO_FILES }}/emacs/*"
  loop:
    - src: "{{ REPO_FILES }}/emacs/init.el"
      dest: "{{ CONFIG_DIR }}/emacs/init.el"
    - src: "{{ REPO_FILES }}/emacs/init.org"
      dest: "{{ CONFIG_DIR }}/emacs/init.org"
    - src: "{{ REPO_FILES }}/emacs/versions/"
      dest: "{{ CONFIG_DIT }}/emacs/straight/versions/"

- name: Template theme
  ansible.builtin.template:
    src: "theme.el"
    dest: "{{ CONFIG_DIR }}/emacs/base16-custom-theme.el"

- name: Copy rclone configuration
  ansible.builtin.file:
    src: "{{ REPO_DIR }}/secret/rclone"
    dest: "{{ CONFIG_DIR }}/rclone"
    state: link

- name: Copy notes-sync to .local/bin
  ansible.builtin.copy:
    src: scripts/notes-sync
    dest: "{{ LOCAL_BIN }}/notes-sync"
    mode: u+x

###################
# SystemD related #
###################
    
- name: Install emacs related services service
  ansible.builtin.copy:
    src: systemd-user/
    dest: "{{ SYSTEMD_DIR }}/"

- name: Enable and start emacs service
  ansible.builtin.systemd:
    name: emacs
    scope: user
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Enable and start notes-sync
  ansible.builtin.service:
    name: notes-sync.timer
    scope: user
    enabled: yes
    state: started
