---

- name: Install Emacs
  ansible.builtin.apt:
    name:
      - emacs
      ## pdf-tools dependencies
      # - libpng-dev
      # - zlib1g-dev
      # - libpoppler-glib-dev
      # - libpoppler-private-dev
      ## plantuml-mode
      - plantuml
  become: yes

- name: Symlink configuration
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ item | replace(REPO_FILES, CONFIG_DIR) }}"
    state: link
  with_fileglob: "{{ REPO_FILES }}/emacs/*"

- name: Install emacs related services service
  ansible.builtin.copy:
    src: systemd-user
    dest: "{{ SYSTEMD_DIR }}/"

- name: Copy notes-sync to .local/bin
  ansible.builtin.copy:
    src: scripts/notes-sync
    dest: "{{ LOCAL_BIN }}/notes-sync"
    mode: u+x

- name: Enable and start emacs service
  ansible.builtin.systemd:
    name: emacs
    scope: user
    enabled: yes
    state: reloaded
    daemon_reload: yes

- name: Enable and start notes-sync
  ansible.builtin.service:
    name: notes-sync.timer
    scope: user
    enabled: yes
    state: started
