---

- name: Install Emacs
  ansible.builtin.apt:
    name: emacs
  become: yes

- name: Copy configuration
  ansible.builtin.copy:
    src: emacs
    dest: "{{ CONFIG_DIR }}"

- name: Install emacs related services service
  ansible.builtin.copy:
    src: systemd/
    dest: "{{ SYSTEMD_USER }}/"

- name: Enable and start emacs service
  ansible.builtin.systemd:
    name: emacs
    scope: user
    enabled: yes
    state: restarted
    daemon_reload: yes
