---

- name: Add ppa for Emacs 28
  ansible.builtin.apt_repository:
    repo: ppa:kelleyk/emacs
  become: yes

- name: Install Emacs
  ansible.builtin.apt:
    name: emacs28
  become: yes

- name: Ensure config directory exists
  ansible.builtin.file:
    path: "{{ CONFIG_DIR }}/emacs"
    state: directory

- name: Symlink configuration
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ item | replace(REPO_FILES, CONFIG_DIR) }}"
    state: link
  with_fileglob: "{{ REPO_FILES }}/emacs/*"

- name: Template theme
  ansible.builtin.template:
    src: "theme.el"
    dest: "{{ CONFIG_DIR }}/emacs/base16-custom-theme.el"

- name: Install emacs related services service
  ansible.builtin.copy:
    src: systemd-user/
    dest: "{{ SYSTEMD_DIR }}/"

- name: Copy notes-sync to .local/bin
  ansible.builtin.copy:
    src: scripts/notes-sync
    dest: "{{ LOCAL_BIN }}/notes-sync"
    mode: u+x

- name: Enable and start emacs service
  ansible.builtin.systemd:
    name: emacs
    scope: user
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Enable and start notes-sync
  ansible.builtin.service:
    name: notes-sync.timer
    scope: user
    enabled: yes
    state: started
