---

- name: Install Emacs
  ansible.builtin.apt:
    name: emacs
  become: yes

- name: Copy configuration
  ansible.builtin.copy:
    src: emacs
    dest: "{{ CONFIG_DIR }}"

- name: Install emacs service
  ansible.builtin.copy:
    src: systemd/
    dest: "{{ SYSTEMD_USER }}/"
