---

- name: Install Emacs
  ansible.builtin.apt: emacs

- name: Copy configuration
  ansible.builtin.copy:
    src: emacs
    dest: "{{ CONFIG_DIR }}"

- name: Install emacs service
  ansible.builtin.copy:
    src: "systemd/{{ item }}"
    dest: "{{ SYSTEMD_USER }}/"
  loop:
    - my-emacs.service
    - sync-notes.service
    - sync-notes.timer
