---

- name: Enable i386
  ansible.builtin.command:
    cmd: dpkg --add-architecture i386
  become: true

- name: Install Lutris
  ansible.builtin.apt:
    name:
      - lutris
      - wine64 
      - wine32 
      - libasound2-plugins:i386 
      - libsdl2-2.0-0:i386 
      - libdbus-1-3:i386 
      - libsqlite3-0:i386
    update_cache: true
  become: true
