---

- name: install MPD
  ansible.builtin.apt:
    name:
      - mpd
      - mpc
      - mpdscribble
  become: yes

- name: Ensure folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ CONFIG_DIR }}/mpd"
    - "{{ HOME }}/.mpdscribble"
    - "{{ SYSTEMD_DIR }}/mpdscribble.service.d"

#####################
# mpd configuration #
#####################

- name: Copy mpd.conf
  ansible.builtin.template:
    src: mpd.conf
    dest: "{{ CONFIG_DIR }}/mpd/mpd.conf"
  notify: mpd

- name: Enable systemd
  ansible.builtin.systemd:
    name: mpd
    enabled: true
    scope: user
  notify: mpd

#############################
# mpdscribble configuration #
#############################

- name: Copy mpdscribble configuration
  ansible.builtin.copy:
    src: "{{ REPO_SECRETS }}/mpdscribble/mpdscribble.conf"
    dest: "{{ HOME }}/.mpdscribble/mpdscribble.conf"
  notify: mpdscribble

- name: Copy mpdscribble override.conf
  ansible.builtin.copy:
    src: mpdscribble.service.d/override.conf
    dest: "{{ SYSTEMD_DIR }}/mpdscribble.service.d/override.conf"
  notify: mpdscribble

- name: Enable mpdscribble
  ansible.builtin.systemd:
    name: mpdscribble
    enabled: true
    scope: user
  notify: mpdscribble
