---

- name: install MPD
  ansible.builtin.apt:
    name:
      - mpd
      - mpdscribble
  become: yes

- name: Ensure mpd folder exists
  ansible.builtin.file:
    path: "{{ CONFIG_DIR }}/mpd"
    state: directory

- name: Copy configuration
  ansible.builtin.template:
    src: mpd.conf
    dest: "{{ CONFIG_DIR }}/mpd/mpd.conf"

- name: Copy mpdscribble override and reload services
  block:
    - name: Copy the override file
      ansible.builtin.copy:
        src: mpdscribble.service.d
        dest: "{{ SYSTEMD_DIR }}/mpdscribble.service.d"
    - name: Reload services
      ansible.builtin.systemd:
        daemon_reload: yes
        scope: user
