---

- name: Clone directory
  ansible.builtin.git:
    repo: "https://github.com/deved99/status-watcher"
    dest: "{{ BUILD_DIR }}/status-watcher"

- name: Build
  ansible.builtin.command:
    cmd: "cargo build --release"
    chdir: "{{ BUILD_DIR }}/status-watcher"

- name: Copy binary to local bin
  ansible.builtin.copy:
    src: "{{ BUILD_DIR }}/status-watcher/target/release/status-watcher"
    dest: "{{ LOCAL_BIN }}/status-watcher"
    mode: "u+x"
    remote_src: true
