---

- name: Ensure old docker packages are not installed
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  become: yes

- name: Packages for Apt over HTTPS
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  become: yes

- name: Install gpg key
  block:
    - name: Remove old gpg public key
      ansible.builtin.file:
        path: "/etc/apt/keyrings/docker.gpg"
        state: absent
    - name: Download docker public key
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        dest: "/tmp/docker.gpg"
    - name: Download docker public key
      ansible.builtin.command: >-
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg
  become: yes

- name: Add repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu
      jammy stable
  become: yes


- name: Install packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
  become: yes
