---

- name: Clone git-toolbelt
  ansible.builtin.git:
    repo: "https://github.com/nvie/git-toolbelt"
    dest: "{{ BUILD_DIR }}/git-toolbelt"

- name: Find git-*
  ansible.builtin.find:
    paths: "{{ BUILD_DIR }}/git-toolbelt"
    patterns: "git-*"
  register: git_paths

- name: Copy git-* to local bin
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ item | replace(BUILD_DIR + '/git-toolbelt', LOCAL_BIN) }}"
    mode: "755"
    remote_src: true
  with_items: "{{ git_paths.files | map(attribute='path') }}"
