---

- name: Find node-token and controller address
  block:
    - ansible.builtin.slurp:
        src: "/var/lib/rancher/k3s/server/node-token"
      register: temp
    - ansible.builtin.set_fact:
        k3s_token: "{{ temp.content | b64decode | regex_replace('\n$', '') }}"
        k3s_url: "https://{{ hostvars[controller_node].k3s_address }}:6443"
  delegate_to: "{{ controller_node }}"

- name: Check token
  ansible.builtin.debug:
    var: install_env
  vars:
    install_env:
      K3S_TOKEN: "{{ k3s_token }}"
      K3S_URL: "{{ k3s_url }}"

- name: Download k3s-install.sh
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /root/k3s-install.sh
    mode: "500"

- name: Ensure additional modules are installed. (Raspberry)
  ansible.builtin.apt:
    name: linux-modules-extra-raspi
  when: is_raspberry is defined and is_raspberry

- name: Install agent
  ansible.builtin.command:
    cmd: >-
      /root/k3s-install.sh agent --flannel-iface {{ k3s_interface }}
  environment:
    K3S_TOKEN: "{{ k3s_token }}"
    K3S_URL: "{{ k3s_url }}"
