---

- name: Install needed packages (ubuntu)
  ansible.builtin.apt:
    name:
      - pipewire
      - pipewire-pulse
      - wireplumber
      - pipewire-audio-client-libraries
      - libspa-0.2-bluetooth
  become: true
  notify: pipewire
  when: distro_short == "ubuntu"

- name: Install needed packages (arch)
  ansible.builtin.apt:
    name:
      - pipewire
      - pipewire-pulse
      - wireplumber
  become: true
  notify: pipewire
  when: distro_short == "arch"

# Disable, stop and mask pulseaudio
- name: Disable pulseaudio
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
    scope: user
  loop:
    - pulseaudio.service
    - pulseaudio.socket

# Enable and start pipewire
- name: Enable pipewire
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    scope: user
  loop:
    - pipewire.service
    - pipewire.socket
    - pipewire-pulse.service
    - pipewire-pulse.socket
    - wireplumber
  notify: pipewire
