--- 

- name: Install packages for awesome
  ansible.builtin.apt:
    name:
      - awesome
      - picom
      - light
      - flameshot
  become: true

- name: Ensure awesome's config dir exists
  ansible.builtin.file:
    path: "{{ CONFIG_DIR }}/awesome"
    state: directory

- name: Symlink configuration
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ item | replace(REPO_FILES, CONFIG_DIR) }}"
    state: link
  with_fileglob: "{{ REPO_FILES }}/awesome/*"

- name: Generate profile specific files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ CONFIG_DIR }}/awesome/{{ item }}"
  loop:
    - colors.lua
    - vars.lua

- name: Restart awesome
  ignore_errors: yes
  ansible.builtin.command: >-
    awesome-client 'awesome.restart()'
