--- 

- name: Install packages for awesome
  ansible.builtin.apt:
    - awesome
    - flameshot

- name: Copy configuration
  ansible.builtin.copy:
    src: awesome
    dest: "{{ CONFIG_DIR }}/awesome"

- name: Restart awesome
  ansible.builtin.command: >-
    awesome-client 'awesome.restart()'
