--- 

- name: Install packages for awesome
  ansible.builtin.apt:
    name:
      - awesome
      - flameshot
  become: true

- name: Copy configuration
  ansible.builtin.shell: >-
    ln -s {{ src }} {{ dest }}
  variables:
    src: "{{ REPO_FILES }}/awesome/*"
    dest: "{{ CONFIG_DIR }}/awesome"

- name: Generate template for colors
  ansible.builtin.template:
    src: colors.lua
    dest: "{{ CONFIG_DIR }}/awesome/colors.lua"

- name: Restart awesome
  ignore_errors: yes
  ansible.builtin.command: >-
    awesome-client 'awesome.restart()'
