--- 

- name: Install packages for awesome
  ansible.builtin.apt:
    name:
      - awesome
      - flameshot

- name: Copy configuration
  ansible.builtin.copy:
    src: awesome
    dest: "{{ CONFIG_DIR }}/awesome"

- name: Restart awesome
  ignore_errors: yes
  ansible.builtin.command: >-
    awesome-client 'awesome.restart()'
