--- 

- name: Install packages for awesome
  ansible.builtin.apt:
    name:
      - awesome
      - flameshot
  become: true

- name: Symlink configuration
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ item | replace(REPO_FILES, CONFIG_DIR) }}"
    state: link
  with_fileglob: "{{ REPO_FILES }}/awesome/*"

- name: Generate template for colors
  ansible.builtin.template:
    src: colors.lua
    dest: "{{ CONFIG_DIR }}/awesome/colors.lua"

- name: Restart awesome
  ignore_errors: yes
  ansible.builtin.command: >-
    awesome-client 'awesome.restart()'
