---

- name: Install MPD (ubuntu)
  ansible.builtin.apt:
    name:
      - mpd
      - mpc
      - mpdscribble
  become: yes
  when: distro_short == "ubuntu"

- name: Install MPD (arch)
  kewlfft.aur.aur:
    name:
      - mpd
      - mpc
      - mpdscribble
  become: yes
  become_user: aur_builder
  when: distro_short == "arch"

- name: Ensure folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ CONFIG_DIR }}/mpd"
    - "{{ HOME }}/.mpdscribble"

#####################
# mpd configuration #
#####################

- name: Copy mpd.conf
  ansible.builtin.template:
    src: mpd.conf
    dest: "{{ CONFIG_DIR }}/mpd/mpd.conf"
  notify: mpd

- name: Enable systemd
  ansible.builtin.systemd:
    name: mpd
    enabled: true
    state: started
    scope: user
  notify: mpd

#############################
# mpdscribble configuration #
#############################

- name: Copy mpdscribble configuration
  ansible.builtin.copy:
    src: "{{ REPO_SECRETS }}/mpdscribble/mpdscribble.conf"
    dest: "{{ HOME }}/.mpdscribble/mpdscribble.conf"
  notify: mpdscribble

- name: Copy mpdscribble override.conf
  ansible.builtin.copy:
    src: mpdscribble.service
    dest: "{{ SYSTEMD_DIR }}/mpdscribble.service"
  notify: mpdscribble

- name: Enable mpdscribble
  ansible.builtin.systemd:
    name: mpdscribble
    enabled: true
    scope: user
  notify: mpdscribble
