---

- name: Install needed packages (ubuntu)
  ansible.builtin.apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - virtinst
      - libosinfo-bin
      - libguestfs-tools
      # For the change permission below
      - acl
    state: present
  become: yes
  when: short_distro == "ubuntu"

- name: Install needed packages (arch)
  ansible.builtin.apt:
    name:
      - qemu-full
      - virt-install
      # For the change permission below
      - acl
    state: present
  become: yes
  when: short_distro == "ubuntu"

- name: Ensure ~ is attraversable by libvirt-qemu
  ansible.posix.acl:
    path: "{{ HOME }}"
    entity: libvirt-qemu
    etype: user
    permissions: rx
    state: present
